---
title: "Pasteurella_mutlocida"
author: "Sarah LE COZ"
date: "06/06/2024"
output: pdf_document
---
```{r}
library(tidyverse)
library(shiny)
library(htmlwidgets)
library(lattice)
library(mvtnorm)
library(DoseFinding)
library(readr)
library(stats)
library(modelr)
library(tidyverse)
library(gridExtra)
library(dplyr)
```

#Importer le data set de PM 033
```{r}
data_set <- read_csv2(
  "N:/4_PROJETS/2022/EMAD_22TQ_Ratio/StageM2_2024/Analyse_R/data_set.csv",
  col_types = cols(
    Idbis = col_character(),
    TIME = col_number(),
    OBS_CFU = col_number(),
    LOG10_CFU = col_number(),
    delta_LOG10 = col_number(),
    CMI = col_number(),
    xCMI = col_number(),
    OUTLIER = col_number(),
    CONC_sulf = col_number(),
    CONC_TMP = col_number()
  ),
  trim_ws = TRUE
)

data_set$ID<-as.factor(data_set$ID)

#Enlever les OUTLIER==1
data_set %>% filter(OUTLIER==0)->data_set
```

#Importer le data set de PM 0359
```{r}
data_set_0359 <- read_csv2(
  "N:/4_PROJETS/2022/EMAD_22TQ_Ratio/StageM2_2024/Analyse_R/data_set_0359.csv",
  col_types = cols(
    Idbis = col_character(),
    TIME = col_number(),
    OBS_CFU = col_number(),
    LOG10_CFU = col_number(),
    delta_LOG10 = col_number(),
    CMI = col_number(),
    xCMI = col_number(),
    OUTLIER = col_number(),
    CONC_sulf = col_number(),
    CONC_TMP = col_number()
  ),
  trim_ws = TRUE
)

data_set_0359$ID<-as.factor(data_set_0359$ID)

#Enlever les OUTLIER==1
data_set_0359 %>% filter(OUTLIER==0)->data_set_0359
```
#Combiner les deux data set
```{r}
combined_data <- bind_rows(data_set, data_set_0359)

combined_data <- combined_data %>%
  mutate(Strain_ID = paste(Strain, ID, sep = "_"))

```

#Courbes de chaque KC
```{r}
library(paletteer)

#Graphe de chaque KC
ggplot(combined_data, aes(x = TIME, y = LOG10_CFU, group = xCMI, color = factor(xCMI))) +
  geom_line() +
  geom_point(shape = 18) +
  scale_color_paletteer_d("ggthemes::gdoc") +
  facet_wrap(~ Strain_ID)
```
#Exemples de KC
```{r}
library(ggplot2)
library(dplyr)
library(paletteer)
library(gridExtra)
library(patchwork)
library(viridis)
library(viridisLite)
library(RColorBrewer)

# Filtrer les données
filtered_data_033_4 <- combined_data %>%
  filter(Strain_ID =="PM_033_4")

filtered_data_033_13 <- combined_data %>%
  filter(Strain_ID =="PM_033_13")

filtered_data_033_7 <- combined_data %>%
  filter(Strain_ID =="PM_033_7")

filtered_data_033_11 <- combined_data %>%
  filter(Strain_ID =="PM_033_11")

filtered_data_033_17 <- combined_data %>%
  filter(Strain_ID =="PM_033_17")

filtered_data_033_27 <- combined_data %>%
  filter(Strain_ID =="PM_033_27")

filtered_data_033_37 <- combined_data %>%
  filter(Strain_ID =="PM_033_37")

# Extraire les limites Y communes
all_data <- bind_rows(filtered_data_033_13, filtered_data_033_17, filtered_data_033_4, filtered_data_033_11, filtered_data_033_7, filtered_data_033_27, filtered_data_033_37)
y_limits <- range(all_data$LOG10_CFU, na.rm = TRUE)

graphe_SMX_033 <- ggplot(filtered_data_033_4, aes(x = TIME, y = LOG10_CFU, group = xCMI, color = factor(xCMI))) +
  geom_line() +
  geom_point(shape = 18) +
  scale_color_paletteer_d("awtools::mpalette") +
  facet_wrap(~ ID) +
  labs(title = "a) SMX, CMI=8 µg/mL",
       x = "Temps (heures)",
       y = "LOG10 (UFC/mL)",
       color = "xCMI") +
  theme_minimal() +
  ylim(y_limits) +
  expand_limits(x = c(min(filtered_data_033_4$TIME) - 1, max(filtered_data_033_4$TIME) + 1)) +
  theme(legend.position = "none")

graphe_SDMX_033 <- ggplot(filtered_data_033_7, aes(x = TIME, y = LOG10_CFU, group = xCMI, color = factor(xCMI))) +
  geom_line() +
  geom_point(shape = 18) +
  scale_color_paletteer_d("awtools::mpalette") +
  facet_wrap(~ ID) +
  labs(title = "b) SDMX, CMI=16 µg/mL",
       x = "Temps (heures)",
       y = "LOG10 (UFC/mL)",
       color = "xCMI") +
  theme_minimal() +
  ylim(y_limits) +
  expand_limits(x = c(min(filtered_data_033_7$TIME) - 1, max(filtered_data_033_7$TIME) + 1)) +
  theme(legend.position = "none")

graphe_SDZ_033 <- ggplot(filtered_data_033_11, aes(x = TIME, y = LOG10_CFU, group = xCMI, color = factor(xCMI))) +
  geom_line() +
  geom_point(shape = 18) +
  scale_color_paletteer_d("awtools::mpalette") +
  facet_wrap(~ ID) +
  labs(title = "c) SDZ, CMI=16 µg/mL",
       x = "Temps (heures)",
       y = "LOG10 (UFC/mL)",
       color = "xCMI") +
  theme_minimal() +
  ylim(y_limits) +
  expand_limits(x = c(min(filtered_data_033_11$TIME) - 1, max(filtered_data_033_11$TIME) + 1)) +
  theme(legend.position = "none")

graphe_TMP_033 <- ggplot(filtered_data_033_13, aes(x = TIME, y = LOG10_CFU, group = xCMI, color = factor(xCMI))) +
  geom_line() +
  geom_point(shape = 18) +
  scale_color_paletteer_d("awtools::mpalette") +
  facet_wrap(~ ID) +
  labs(title = "g) TMP, CMI=0.065 µg/mL",
       x = "Temps (heures)",
       y = "LOG10 (UFC/mL)",
       color = "xCMI") +
  theme_minimal() +
  ylim(y_limits) +
  expand_limits(x = c(min(filtered_data_033_13$TIME) - 1, max(filtered_data_033_13$TIME) + 1)) +
  theme(legend.position = "none")


graphe_SMX_1_19_033 <- ggplot(filtered_data_033_17, aes(x = TIME, y = LOG10_CFU, group = xCMI, color = factor(xCMI))) +
  geom_line() +
  geom_point(shape = 18) +
  scale_color_paletteer_d("awtools::mpalette") +
   facet_wrap(~ ID) +
  labs(title = paste("d) SMX 1:19", "CMI=0.016/0.3 µg/mL", sep = "\n"),
       x = "Temps (heures)",
       y = "LOG10 (UFC/mL)",
       color = "xCMI") +
  theme_minimal() +
  ylim(y_limits) +
  expand_limits(x = c(min(filtered_data_033_17$TIME) - 1, max(filtered_data_033_17$TIME) + 1))

graphe_SDMX_1_99_033 <- ggplot(filtered_data_033_27, aes(x = TIME, y = LOG10_CFU, group = xCMI, color = factor(xCMI))) +
  geom_line() +
  geom_point(shape = 18) +
  scale_color_paletteer_d("awtools::mpalette") +
   facet_wrap(~ ID) +
  labs(title = paste("e) SDMX 1:99", "CMI=0.015/1.5 µg/mL", sep = "\n"),
       x = "Temps (heures)",
       y = "LOG10 (UFC/mL)",
       color = "xCMI") +
  theme_minimal() +
  ylim(y_limits) +
  expand_limits(x = c(min(filtered_data_033_27$TIME) - 1, max(filtered_data_033_27$TIME) + 1))

graphe_SDZ_1_999_033 <- ggplot(filtered_data_033_37, aes(x = TIME, y = LOG10_CFU, group = xCMI, color = factor(xCMI))) +
  geom_line() +
  geom_point(shape = 18) +
  scale_color_paletteer_d("awtools::mpalette") +
   facet_wrap(~ ID) +
  labs(title = paste("f) SDZ 1:999", "CMI=0.0078/7.8 µg/mL", sep = "\n"),
       x = "Temps (heures)",
       y = "LOG10 (UFC/mL)",
       color = "xCMI") +
  theme_minimal() +
  ylim(y_limits) +
  expand_limits(x = c(min(filtered_data_033_37$TIME) - 1, max(filtered_data_033_37$TIME) + 1))

combined_plot <- (graphe_SMX_033 + graphe_SDMX_033 + graphe_SDZ_033 + graphe_SMX_1_19_033 + graphe_SDMX_1_99_033 + graphe_SDZ_1_999_033 + graphe_TMP_033 + plot_layout(ncol = 3))

ggsave("combined_plot.png", combined_plot, width = 9, height = 8)
```

#AUC
```{r}
# Fonction pour calculer l'aire sous une courbe en utilisant la methode des trapezes
calculate_area_trapezoids <- function(x, y) {
  # S'assurer que les donnees sont triees par x
  sorted_indices <- order(x)
  x <- x[sorted_indices]
  y <- y[sorted_indices]
  # Calculer l'aire en utilisant la methode des trapezes
  area <- sum(diff(x) * (head(y, -1) + tail(y, -1)) / 2)
  return(area)
}

# Agreger les donnees par ID, xCMI et TIME, en calculant la moyenne de LOG10_CFU pour chaque groupe
grouped_data_AUC <- combined_data %>%
  group_by(Strain_ID, xCMI, TIME, CONC_TMP, ratio, MOLECULE) %>%
  summarize(avg_LOG10_CFU = mean(LOG10_CFU, na.rm = TRUE), .groups = 'drop')

# Calculer l'aire sous chaque courbe pour chaque combinaison de ID et xCMI
areas <- grouped_data_AUC %>%
  group_by(Strain_ID, xCMI, CONC_TMP, ratio, MOLECULE) %>%
  summarize(area_under_curve = calculate_area_trapezoids(TIME, avg_LOG10_CFU), .groups = 'drop')

# AUC : histogramme par xCMI
ggplot(areas, aes(x = factor(xCMI), y = area_under_curve, fill = factor(xCMI))) +
  geom_bar(stat = "identity") +
  facet_wrap(~ Strain_ID) +
  labs(title = "Aire sous chaque courbe par ID et xCMI", x = "xCMI", y = "Aire sous la courbe") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_fill_discrete(name = "xCMI")
```
#Equation 1 : Croissance moyenne de l'inoculum
```{r}
#inoculum moyen obtenu apres exposition à ATB pendant 24h (ou 8h)

Ix <- ifelse(
  areas$Strain_ID %in% c("PM_033_3", "PM_033_5", "PM_033_19", "PM_033_33", "PM_0359_3"), 
  areas$area_under_curve / 8, 
  ifelse(
    areas$Strain_ID == "PM_0359_29" & areas$xCMI %in% c(4, 8, 16), 
    areas$area_under_curve / 8, 
    ifelse(
      areas$Strain_ID == "PM_0359_35" & areas$xCMI %in% c(4, 16), 
      areas$area_under_curve / 8,
      ifelse(
        areas$Strain_ID %in% c("PM_0359_1", "PM_0359_6") & areas$xCMI %in% c(2, 4, 8), 
        areas$area_under_curve / 8,
        areas$area_under_curve / 24))))


tableau_Ix <- data.frame(Strain_ID = areas$Strain_ID, xCMI = areas$xCMI, Ix = Ix)

#taille de l'inoculum de depart
# Filtrer les donnees pour obtenir les valeurs à TIME = 0.00 pour chaque combinaison de xCMI et ID
valeurs_inoculum <- combined_data %>%
  filter(TIME == 0.00) %>%
  select(Strain_ID, xCMI, LOG10_CFU)

IBasal<-valeurs_inoculum$LOG10_CFU
  
#croissance moyenne de l'incoulum sur 24h
delta_i_x<-Ix-IBasal

tableau_delta_i_x<- data.frame(Strain_ID = areas$Strain_ID, xCMI = areas$xCMI, ratio = areas$ratio, MOLECULE =areas$MOLECULE, delta_i_x = delta_i_x)

tableau_delta_i_x <- data.frame(Strain_ID = areas$Strain_ID,
                                xCMI = areas$xCMI,
                                delta_i_x = delta_i_x,
                                CONC_TMP = areas$CONC_TMP,
                                ratio = areas$ratio,
                                MOLECULE =areas$MOLECULE)
```

#Filtrer les données par MOLECULE et ratio
```{r}
#ATB seuls
SMX<- tableau_delta_i_x %>%
  filter(MOLECULE == "SMX" & ratio == 0)

ggplot(SMX, aes(x = xCMI)) +
  geom_point(aes(y = delta_i_x)) +
  labs(title = "SMX",
       x = "xCMI",
       y = "Delta I X (delta_i_x)") +
  theme_minimal()

SDMX<- tableau_delta_i_x %>%
  filter(MOLECULE == "SDMX" & ratio == 0)

ggplot(SDMX, aes(x = xCMI)) +
  geom_point(aes(y = delta_i_x)) +
  labs(title = "SDMX",
       x = "xCMI",
       y = "Delta I X (delta_i_x)") +
  theme_minimal()

SDZ<- tableau_delta_i_x %>%
  filter(MOLECULE == "SDZ" & ratio == 0)

ggplot(SDZ, aes(x = xCMI)) +
  geom_point(aes(y = delta_i_x)) +
  labs(title = "SDZ",
       x = "xCMI",
       y = "Delta I X (delta_i_x)") +
  theme_minimal()

TMP<- tableau_delta_i_x %>%
  filter(MOLECULE == "TMP" & ratio == 0)

ggplot(TMP, aes(x = xCMI)) +
  geom_point(aes(y = delta_i_x)) +
  labs(title = "TMP",
       x = "xCMI",
       y = "Delta I X (delta_i_x)") +
  theme_minimal()

#1_19
SMX_1_19<- tableau_delta_i_x %>%
  filter(MOLECULE == "SMX/TMP" & ratio == "1_19")

SDMX_1_19<- tableau_delta_i_x %>%
  filter(MOLECULE == "SDMX/TMP" & ratio == "1_19")

ggplot(SDMX_1_19, aes(x = xCMI)) +
  geom_point(aes(y = delta_i_x)) +
  labs(title = "SDMX 1_19",
       x = "xCMI",
       y = "Delta I X (delta_i_x)") +
  theme_minimal()

SDZ_1_19<- tableau_delta_i_x %>%
  filter(MOLECULE == "SDZ/TMP" & ratio == "1_19")

#1_99
SMX_1_99<- tableau_delta_i_x %>%
  filter(MOLECULE == "SMX/TMP" & ratio == "1_99")

SDMX_1_99<- tableau_delta_i_x %>%
  filter(MOLECULE == "SDMX/TMP" & ratio == "1_99")

ggplot(SDMX_1_99, aes(x = xCMI)) +
  geom_point(aes(y = delta_i_x)) +
  labs(title = "SDMX 1_99",
       x = "xCMI",
       y = "Delta I X (delta_i_x)") +
  theme_minimal()

SDZ_1_99<- tableau_delta_i_x %>%
  filter(MOLECULE == "SDZ/TMP" & ratio == "1_99")

#1_999
SMX_1_999<- tableau_delta_i_x %>%
  filter(MOLECULE == "SMX/TMP" & ratio == "1_999")

SDMX_1_999<- tableau_delta_i_x %>%
  filter(MOLECULE == "SDMX/TMP" & ratio == "1_999")

ggplot(SDMX_1_999, aes(x = xCMI)) +
  geom_point(aes(y = delta_i_x)) +
  labs(title = "SDMX_1_999",
       x = "xCMI",
       y = "Delta I X (delta_i_x)") +
  theme_minimal()

SDZ_1_999<- tableau_delta_i_x %>%
  filter(MOLECULE == "SDZ/TMP" & ratio == "1_999")
```

#Equation 2 : Modele sigmoide Emax, modelisation de la croissance moyenne de l'inoculum
```{r}
start_values_SMX <- list(
  delta_i_max = 3.63,
  delta_i_min = -3.53,
  EC2LOG = 1,
  gam = 1
)

start_values_SDMX <- list(
  delta_i_max = 3.84,
  delta_i_min = -3.9,
  EC2LOG = 1.10,
  gam = 1.13
)

start_values_SDZ <- list(
  delta_i_max = 4.1,
  delta_i_min = -1.53,
  EC2LOG = 1,
  gam = 1
)

start_values_TMP <- list(
  delta_i_max = 3.95,
  delta_i_min = -3.85,
  EC2LOG = 0.4,
  gam = 1
)

start_values_1_19 <- list(
  delta_i_max = 4.05,
  delta_i_min = -3.8,
  EC2LOG = 0.2,
  gam = 1
)

start_values_1_99 <- list(
  delta_i_max = 3.97,
  delta_i_min = -4.2,
  EC2LOG = 0.6,
  gam = 1
)

start_values_1_999 <- list(
  delta_i_max = 3.8,
  delta_i_min = -4.1,
  EC2LOG = 0.2,
  gam = 1
)

library(minpack.lm)

#ATBs
smx <- nlsLM(
 delta_i_x ~ delta_i_max - ((delta_i_max - delta_i_min) * ((xCMI / EC2LOG)^gam) / (((-2 - delta_i_min) / delta_i_max + 2) + (xCMI / EC2LOG)^gam)),
  data = SMX,
  start = start_values_SMX,
  control = nls.lm.control(maxiter = 200))

parameters_smx <- summary(smx)
coef_SMX<-coef(parameters_smx)

sdmx <- nlsLM(
 delta_i_x ~ delta_i_max - ((delta_i_max - delta_i_min) * ((xCMI / EC2LOG)^gam) / (((-2 - delta_i_min) / delta_i_max + 2) + (xCMI / EC2LOG)^gam)),
  data = SDMX,
  start = start_values_SDMX,
  control = nls.lm.control(maxiter = 200))

parameters_sdmx <- summary(sdmx)
coef_SDMX<-coef(parameters_sdmx)

sdz <- nlsLM(
 delta_i_x ~ delta_i_max - ((delta_i_max - delta_i_min) * ((xCMI / EC2LOG)^gam) / (((-2 - delta_i_min) / delta_i_max + 2) + (xCMI / EC2LOG)^gam)),
  data = SDZ,
  start = start_values_SDZ,
  control = nls.lm.control(maxiter = 200))

parameters_sdz <- summary(sdz)
coef_SDZ<-coef(parameters_sdz)

tmp <- nlsLM(
 delta_i_x ~ delta_i_max - ((delta_i_max - delta_i_min) * ((xCMI / EC2LOG)^gam) / (((-2 - delta_i_min) / delta_i_max + 2) + (xCMI / EC2LOG)^gam)),
  data = TMP,
  start = start_values_TMP,
  control = nls.lm.control(maxiter = 200))

parameters_tmp <- summary(tmp)
coef_TMP<-coef(parameters_tmp)

#1_19
smx_1_19 <- nlsLM(
 delta_i_x ~ delta_i_max - ((delta_i_max - delta_i_min) * ((xCMI / EC2LOG)^gam) / (((-2 - delta_i_min) / delta_i_max + 2) + (xCMI / EC2LOG)^gam)),
  data = SMX_1_19,
  start = start_values_1_19,
  control = nls.lm.control(maxiter = 200))

parameters_smx_1_19 <- summary(smx_1_19)
coef_SMX_1_19<-coef(parameters_smx_1_19)

sdmx_1_19 <- nlsLM(
 delta_i_x ~ delta_i_max - ((delta_i_max - delta_i_min) * ((xCMI / EC2LOG)^gam) / (((-2 - delta_i_min) / delta_i_max + 2) + (xCMI / EC2LOG)^gam)),
  data = SDMX_1_19,
  start = start_values_1_19,
  control = nls.lm.control(maxiter = 200))

parameters_sdmx_1_19 <- summary(sdmx_1_19)
coef_SDMX_1_19<-coef(parameters_sdmx_1_19)

sdz_1_19 <- nlsLM(
 delta_i_x ~ delta_i_max - ((delta_i_max - delta_i_min) * ((xCMI / EC2LOG)^gam) / (((-2 - delta_i_min) / delta_i_max + 2) + (xCMI / EC2LOG)^gam)),
  data = SDZ_1_19,
  start = start_values_1_19,
  control = nls.lm.control(maxiter = 200))

parameters_sdz_1_19 <- summary(sdz_1_19)
coef_SDZ_1_19<-coef(parameters_sdz_1_19)

#1_99
smx_1_99 <- nlsLM(
 delta_i_x ~ delta_i_max - ((delta_i_max - delta_i_min) * ((xCMI / EC2LOG)^gam) / (((-2 - delta_i_min) / delta_i_max + 2) + (xCMI / EC2LOG)^gam)),
  data = SMX_1_99,
  start = start_values_1_99,
  control = nls.lm.control(maxiter = 200))

parameters_smx_1_99 <- summary(smx_1_99)
coef_SMX_1_99<-coef(parameters_smx_1_99)

sdmx_1_99 <- nlsLM(
 delta_i_x ~ delta_i_max - ((delta_i_max - delta_i_min) * ((xCMI / EC2LOG)^gam) / (((-2 - delta_i_min) / delta_i_max + 2) + (xCMI / EC2LOG)^gam)),
  data = SDMX_1_99,
  start = start_values_1_99,
  control = nls.lm.control(maxiter = 200))

parameters_sdmx_1_99 <- summary(sdmx_1_99)
coef_SDMX_1_99<-coef(parameters_sdmx_1_99)

sdz_1_99 <- nlsLM(
 delta_i_x ~ delta_i_max - ((delta_i_max - delta_i_min) * ((xCMI / EC2LOG)^gam) / (((-2 - delta_i_min) / delta_i_max + 2) + (xCMI / EC2LOG)^gam)),
  data = SDZ_1_99,
  start = start_values_1_99,
  control = nls.lm.control(maxiter = 200))

parameters_sdz_1_99 <- summary(sdz_1_99)
coef_SDZ_1_99<-coef(parameters_sdz_1_99)

#1_999
smx_1_999 <- nlsLM(
 delta_i_x ~ delta_i_max - ((delta_i_max - delta_i_min) * ((xCMI / EC2LOG)^gam) / (((-2 - delta_i_min) / delta_i_max + 2) + (xCMI / EC2LOG)^gam)),
  data = SMX_1_999,
  start = start_values_1_999,
  control = nls.lm.control(maxiter = 200))

parameters_smx_1_999 <- summary(smx_1_999)
coef_SMX_1_999<-coef(parameters_smx_1_999)

sdmx_1_999 <- nlsLM(
 delta_i_x ~ delta_i_max - ((delta_i_max - delta_i_min) * ((xCMI / EC2LOG)^gam) / (((-2 - delta_i_min) / delta_i_max + 2) + (xCMI / EC2LOG)^gam)),
  data = SDMX_1_999,
  start = start_values_1_999,
  control = nls.lm.control(maxiter = 200)) 

parameters_sdmx_1_999 <- summary(sdmx_1_999)
coef_SDMX_1_999<-coef(parameters_sdmx_1_999)

sdz_1_999 <- nlsLM(
 delta_i_x ~ delta_i_max - ((delta_i_max - delta_i_min) * ((xCMI / EC2LOG)^gam) / (((-2 - delta_i_min) / delta_i_max + 2) + (xCMI / EC2LOG)^gam)),
  data = SDZ_1_999,
  start = start_values_1_999,
  control = nls.lm.control(maxiter = 200))

parameters_sdz_1_999 <- summary(sdz_1_999)
coef_SDZ_1_999<-coef(parameters_sdz_1_999)

all_coef <- bind_rows(
  coef_SMX, coef_SDMX, coef_SDZ, coef_TMP,
  coef_SMX_1_19, coef_SDMX_1_19, coef_SDZ_1_19,
  coef_SMX_1_99, coef_SDMX_1_99, coef_SDZ_1_99,
  coef_SMX_1_999, coef_SDMX_1_999, coef_SDZ_1_999
)

library(writexl)
write_xlsx(all_coef, path = "parameters_PD.xlsx")
```

#graphe PD ATBs seuls
```{r}
all_Sulfa <- data.frame(xCMI=seq(0, 70, by=0.1))  # creer un range de concentrations en ATB pour fitter le modèle, adapté au range existant dans les manips (exemple sulfa seul, aller de 0 à 512)

all_Sulfa$fitsmx <-predict(smx, all_Sulfa)  # calcules le fit du modèle pour smx sur ce range de concentrations
all_Sulfa$fitsdmx <-predict(sdmx, all_Sulfa) # calcules le fit du modèle pour sdmx sur ce range de concentrations
all_Sulfa$fitsdz <-predict(sdz, all_Sulfa)  # calcules le fit du modèle pour sdz sur ce range de concentrations

all_TMP <- data.frame(xCMI=seq(0.001, 70, by=0.02))
all_TMP$fittmp <-predict(tmp, all_TMP)

all_Sulfa_ratios <- data.frame(xCMI=seq(0, 20, by=0.005))

all_Sulfa_ratios$fitsmx_1_19 <- predict(smx_1_19, all_Sulfa_ratios)
all_Sulfa_ratios$fitsdmx_1_19 <- predict(sdmx_1_19, all_Sulfa_ratios)
all_Sulfa_ratios$fitsdz_1_19 <- predict(sdz_1_19, all_Sulfa_ratios)

all_Sulfa_ratios$fitsmx_1_99 <- predict(smx_1_99, all_Sulfa_ratios)
all_Sulfa_ratios$fitsdmx_1_99 <- predict(sdmx_1_99, all_Sulfa_ratios)
all_Sulfa_ratios$fitsdz_1_99 <- predict(sdz_1_99, all_Sulfa_ratios)

all_Sulfa_ratios$fitsmx_1_999 <- predict(smx_1_999, all_Sulfa_ratios)
all_Sulfa_ratios$fitsdmx_1_999 <- predict(sdmx_1_999, all_Sulfa_ratios)
all_Sulfa_ratios$fitsdz_1_999 <- predict(sdz_1_999, all_Sulfa_ratios)

PD_seul <- ggplot() +
  geom_point(data=SMX, aes(x = xCMI, y = delta_i_x, color = "SMX")) +  
  geom_line(data=all_Sulfa, aes(x = xCMI, y = fitsmx, color = "SMX")) +
  geom_point(data=SDMX, aes(x = xCMI, y = delta_i_x, color = "SDMX")) +  
  geom_line(data=all_Sulfa, aes(x = xCMI, y = fitsdmx, color = "SDMX")) +
  geom_point(data=SDZ, aes(x = xCMI, y = delta_i_x, color = "SDZ")) +  
  geom_line(data=all_Sulfa, aes(x = xCMI, y = fitsdz, color = "SDZ")) +
  geom_point(data=TMP, aes(x = xCMI, y = delta_i_x, color = "TMP")) +  
  geom_line(data=all_TMP, aes(x = xCMI, y = fittmp, color = "TMP")) +
  scale_color_manual(name = "",
                     values = c("SMX" = "blue", "SDMX" = "darkgreen", "SDZ" = "red", "TMP" = "black"),
                     labels = c("SMX", "SDMX", "SDZ", "TMP")) +
  labs(title = "a",
       x = "Concentration (xCMI)",
       y = "Croissance moyenne\n de l'inoculum (ΔlogUFC/mL)") +
  scale_x_continuous(trans = "log2",breaks=c(0,0.25,0.5,1,2,4,8,16,32,64)) +
  theme_bw()

print(PD_seul)

PD_SMX <- ggplot() +
  geom_point(data=SMX_1_19, aes(x = xCMI, y = delta_i_x, color = "SMX_1_19")) +
  geom_line(data=all_Sulfa_ratios, aes(x = xCMI, y = fitsmx_1_19, color = "SMX_1_19")) +
  geom_point(data=SMX_1_99, aes(x = xCMI, y = delta_i_x, color = "SMX_1_99")) +  
  geom_line(data=all_Sulfa_ratios, aes(x = xCMI, y = fitsmx_1_99, color = "SMX_1_99")) +
  geom_point(data=SMX_1_999, aes(x = xCMI, y = delta_i_x, color = "SMX_1_999")) +  
  geom_line(data=all_Sulfa_ratios, aes(x = xCMI, y = fitsmx_1_999, color = "SMX_1_999")) +
  scale_color_manual(name = "",
                     values = c("SMX_1_19" = "darkseagreen", "SMX_1_99" = "limegreen", "SMX_1_999" = "darkgreen"),
                     labels = c("SMX 1:19", "SMX 1:99", "SMX 1:999")) +
  labs(title = "b",
       x = "Concentration TMP (xCMI)",
       y = "Croissance moyenne\n de l'inoculum (ΔlogUFC/mL)") +
  scale_x_continuous(trans = "log2",breaks=c(0,0.25,0.5,1,2,4,8,16,32,64)) +
  theme_bw()

PD_SDMX <- ggplot() +
  geom_point(data=SDMX_1_19, aes(x = xCMI, y = delta_i_x, color = "SDMX_1_19")) +
  geom_line(data=all_Sulfa_ratios, aes(x = xCMI, y = fitsdmx_1_19, color = "SDMX_1_19")) +
  geom_point(data=SDMX_1_99, aes(x = xCMI, y = delta_i_x, color = "SDMX_1_99")) +  
  geom_line(data=all_Sulfa_ratios, aes(x = xCMI, y = fitsdmx_1_99, color = "SDMX_1_99")) +
  geom_point(data=SDMX_1_999, aes(x = xCMI, y = delta_i_x, color = "SDMX_1_999")) +  
  geom_line(data=all_Sulfa_ratios, aes(x = xCMI, y = fitsdmx_1_999, color = "SDMX_1_999")) + 
  scale_color_manual(name = "",
                     values = c("SDMX_1_19" = "lightcoral", "SDMX_1_99" = "red", "SDMX_1_999" = "darkred"),
                     labels = c("SDMX 1:19", "SDMX 1:99", "SDMX 1:999")) +
  labs(title = "c",
       x = "Concentration TMP (xCMI)",
       y = "Croissance moyenne\n de l'inoculum (ΔlogUFC/mL)") +
  scale_x_continuous(trans = "log2",breaks=c(0,0.25,0.5,1,2,4,8,16,32,64))+
  theme_bw()

PD_SDZ <- ggplot() +
  geom_point(data=SDZ_1_19, aes(x = xCMI, y = delta_i_x, color="SDZ_1_19")) +
  geom_line(data=all_Sulfa_ratios, aes(x = xCMI, y = fitsdz_1_19, color="SDZ_1_19")) +
  geom_point(data=SDZ_1_99, aes(x = xCMI, y = delta_i_x, color="SDZ_1_99")) +  
  geom_line(data=all_Sulfa_ratios, aes(x = xCMI, y = fitsdz_1_99, color="SDZ_1_99")) +
  geom_point(data=SDZ_1_999, aes(x = xCMI, y = delta_i_x, color="SDZ_1_999")) +  
  geom_line(data=all_Sulfa_ratios, aes(x = xCMI, y = fitsdz_1_999, color="SDZ_1_999")) +
  scale_color_manual(name="",
                     values=c("SDZ_1_19"="deepskyblue", "SDZ_1_99" = "turquoise4", "SDZ_1_999" = "blue"),
                     labels=c("SDZ 1:19", "SDZ 1:99", "SDZ 1:999")) +
  labs(title="d",
       x="Concentration TMP (xCMI)",
       y="Croissance moyenne\n de l'inoculum (ΔlogUFC/mL)") +
  scale_x_continuous(trans = "log2",breaks=c(0,0.25,0.5,1,2,4,8,16,32,64))+
  theme_bw()

PD_combined_plot <- (PD_seul + PD_SMX + PD_SDMX + PD_SDZ + plot_layout(ncol = 1))

ggsave("PD_combined_plot.png", PD_combined_plot, width = 9, height = 10)
```